### PR TITLE
Added undeploy_action operation

### PR DESCRIPTION
**Pull request by brosano**
You can specify a different action from the defaut

Signed-off-by: brosano <brahyan.rosano@gmail.com>

### CODE REVIEW

**Comment by sgutermann** [comment]
Sorry for asking, but what exactly does this do? Things like poweroff or undeploy speak for themselves, but what is an undeploy_action and how would one use it?

**Comment by brosano** [comment]
Undeploy does an undeploy with the default action, you can not specify another action and doing undeploy leaves you with a partially running vApp. With undeploy_action you can specify another action like poweroff or shutdown (to gracefully shutdown the vm). It's done with the same function from pyvcloud.

It can be used in a similar way than other functions, but specifying the action that will be taken. 

  - name: Shutting down vapp
    vcd_vapp:
      vapp_name: "vApp_name"
      vdc: "VDC-NAME"
      operation: "undeploy_action"
      undeploy_action: "shutdown"

**Comment by mukultaneja** [comment]
Hi @brosano, @sgutermann I looked into this pull request. I would like to suggest instead of including a new parameter why not to make "shutdown" or "poweroff" as a by default action to un deploy a vApp. Please share your views and help me to address this PR.

**Comment by sgutermann** [comment]
Well either way. In the meantime I tottaly understand why @brosano even built and though about this. Thank you for that. Having those partial vApps hanging around means pure money or shutting them down by hand.

**Comment by mukultaneja** [comment]
@sgutermann thanks for the reply. Let's make "powerOff" as a by default action to un deploy a vapp.

**Comment by mukultaneja** [comment]
@sgutermann @brosano I have added this small change with ed0282c4a82394136d39202b62460079fc7f9885. 
@brosano Thanks for submitting this PR and apologies for this late reply. Please review the change and allow me to close this PR and issue. Feel free to reopen the issue if you find any concern.

**Comment by brosano** [comment]
This changes leave us in the same scenario, the default action was powerOff, the difference is that it was the default on the pyvcloud module, and now this is the default on the ansible-module (that depends on pyvcloud module).

I suggested to use "shutdown" because it shutdown the OS gracefully instead a "pulling the power cable" as poweroff does.

In any case, a parameter to chose the option that better fit your needs would be great.

**Pull request closed without merging**
