### PR TITLE
Additional functionality

### PR DESCRIPTION
**Pull request by robinelfrink**
We've added some functionality we needed.

### CODE REVIEW

**Comment by rthomson** [comment]
6a56846 would be useful functionality for us as well.

**Comment by mukultaneja** [comment]
Thanks, @robinelfrink for the pull requests. I am in the process of validating the functionalities and getting following errors while adding, 

- vcd_vapp_vm_disk

screen shot 2018-10-03 at 1 30 53 pm

- vcd_vapp_network

screen shot 2018-10-03 at 1 31 52 pm

- vcd_vapp_vm
https://github.com/vmware/ansible-module-vcloud-director/blob/7b5d204f0d9d1366ce14241fe99020bd2aa50845/modules/vcd_vapp_vm.py#L358

Here, at my end `productsection` is getting `None` as a value and I am not clear with this use case as well, is it for building vapp from OVF?

**Comment by robinelfrink** [comment]
> * vcd_vapp_vm_disk

Here I copied parts of `vapp.add_disk_to_vm()` from `pyvcloud` because that fits our needs at the moment. The code assumes (as does `pyvcloud`) there is at least one disk already present in the vm.

> * vcd_vapp_network

A copy/paste error, fixed in the last commit.

> * vcd_vapp_vm
[...]
> Here, at my end `productsection` is getting `None` as a value and I am not clear with this use case as well, is it for building vapp from OVF?

Yes. However, I did not take into account the possibility of an OVF without `<ovf:Property>` section. I have a fix ready for this but need to test it first.


Thanks for looking at the PR!

**Comment by mukultaneja** [comment]
@robinelfrink, please confirm if you are considering building `Vapp` from `ovf` through `the productSection` code block!

**Pull request merged**
