### PR TITLE
Added support for creating users and vdc in a given organization.

### PR DESCRIPTION
**Pull request by joostcoelingh**
This allows for creating a complete environment on vcd i.e. Create a new org, create a user in the new org, create a vdc in the new org. 

Previously this was not possible as the user and vdc modules would create the resources in the org in which the logged in user resides.

### CODE REVIEW

**Comment by mukultaneja** [comment]
Thanks, @joostcoelingh for submitting a pull request. But I wonder if this is a legitimate use case to be added!

**Comment by joostcoelingh** [comment]
@mukultaneja, it is for our use case otherwise we can't fully automate the deployment of an org, org_vdc, users & other functionality in the new org. We can create users in an organisation using the module, however that requires you to first manually create a user in the org (other module options depends on being able to login in the org to perform tasks).

These changes in the PR allows you to create a user in a fresh org so the rest of the modules functions can be used without manually creating a user first.

**Comment by mukultaneja** [comment]
@joostcoelingh, It make sense to add `org_name` in `vcd_user` so that you can create a new user for the fresh org but I think we should not add `org_name` in  `vcd_org_vdc` because once you have the user for a org then you can log in to the org and create vdc for it.

**Comment by MichalTaratuta** [comment]
@mukultaneja with regards to `vcd_org_vdc` why would you like to switch to an `Organization Administrator`? I can see @joostcoelingh point that if I provision an organisation I will be doing it with a credentials of role `System Administrator`. Why not to have both this would allow for flexibility. 

@mukultaneja is it possible to have it marge any time soon? I'm really waiting for this feature and I don't want to be running of non master branch.

**Pull request merged**
