### PR TITLE
Add operations list_users, list_vdcs, set_metadata

### PR DESCRIPTION
**Pull request by moonrail**
Hello altogether,

~~first~~ [second](https://github.com/vmware/ansible-module-vcloud-director/pull/88) pull request, so please be patient with me.

In my company PlusServer we use several vCD in different regions, so I took the time and made some changes (I hope improvements) all over the board for these modules.

I will contribute them bit by bit, starting with something small here: `vcd_org.py`

Here we needed just some additional operations to get info on orgs.

# list_users
returns key `users` with dicts of users as per pyvclouds [org.list_users()](https://github.com/vmware/pyvcloud/blob/master/pyvcloud/vcd/org.py#L1024) and [utils.to_dict()](https://github.com/vmware/pyvcloud/blob/master/pyvcloud/vcd/utils.py#L680)

# list_vdcs
returns key `vdcs` with dicts of vdcs as per pyvclouds [org.list_vdcs()](https://github.com/vmware/pyvcloud/blob/master/pyvcloud/vcd/org.py#L1611)

# set_metadata
expects key `metadata` and sets metadata on org via pyvclouds [metadata.set_metadata()](https://github.com/vmware/pyvcloud/blob/master/pyvcloud/vcd/metadata.py#L90)
<br>Input-Data:
```
metadata:
  - state: 'present'                                             # optional, present (will also update value), absent, default: present
    name: 'keyX'                                                 # mandatory, unique name of metadata-entry
    value: 'valueY'                                              # mandatory, if state present, else optional as it will be ignored
    type: 'STRING'                                               # optional, STRING, NUMBER, BOOLEAN, DATA_TIME, default: STRING
    visibility: 'READONLY'                                       # optional, PRIVATE, READONLY, READ_WRITE, default: READONLY
```

Following are some of the bigger changes that I can provide in following PRs.
# Possible future PRs
## all modules
- added handling for newer pyvcloud-versions (raises no EntityNotFoundException anymore)
- added parameter org_name to all modules to be usable to define a different target Organization from what the user is logged in to
## vcd_org_vdc
- added metadata creation on states "present" and "update" as well as deletion on state "update"
- added operation to set metadata on storage_profiles / storage policies
- added operation to list all vApps of a vdc
- added operation to list all networks of a vdc
- removed any defaults as this is not good practice and can not be combined for update-tasks where you want the user to define what to update
- added proper update-state, as previously nothing but "IsEnabled" of a vdc could be updated (and was not supported anymore "OperationNotSupportedException")
## vcd_vapp
- changed network to be optional for cloning from Template/vApp-VM
- added operation shutdown
- added metadata creation on states "present" and "update" as well as deletion on state "update"
## vcd_catalog
- added operation to share catalogs with specific Organizations
## vcd_vdc_network
- added possibility to delete networks without specifiying network type to vcd_vdc_network
## vcd_vapp_vm
- added parameter force_guest_customizations and power_on handling for operation "deploy"
- added operation "upgrade_virtual_hardware"
- added metadata creation on states "present" and "update" as well as deletion on state "update"
## vcd_vapp_vm_nic
- fixed NIC handling to NOT update nics, if no changes are necessary
- added primary, connected and adapter-type handling
## vcd_vdc_gateway
- changed input vars and creation handling of edge gateways
- added firewall-rule-handling and implemented it besides pyvcloud, as pyvclouds solution does not work with gateways in formfactor compact
- added NAT-rule-handling (leads to new python requirement: netaddr)
- updating of edge gateways in vcd_vdc_gateway.py
  - add, remove (and split) suballocated ip-ranges
  - editing rate-limits
  - add/remove subnets
  - add/remove external networks
## new module: vcd_platform
- following operations are included:
  - list all provider vdcs of a vCloud Director
  - list all network pools of a vCloud Director
  - get vcenter of a pvdc
  - get the least used provider vdc of a vCloud Director
  - get the provider vdc of a vdc
  - get the network pool of a provider vdc
  - get all storage profiles of a provider vdc
## new module: vcd_external_network
- can as of now only: add, remove vCD external networks

### CODE REVIEW

**Comment by mukultaneja** [comment]
Hi @moonrail, thanks for submitting a PR for new features. It would be so helpful if you add following with the PR,

1. Tasks into the existing vcd_org role's playbook just to cover how to use these new features
2. Update the Org docs
3. Remove the Binary file which you might add accidentally with the PR

**Comment by mukultaneja** [comment]
Hi @moonrail, apologies to reply this late on to the PR. Would you still like to merge this PR?

**Comment by moonrail** [comment]
Hi @mukultaneja,
yep, although we've developed our internal fork even further now, so not everything will be conflict-free mergeable.

**Comment by mukultaneja** [comment]
@moonrail sure, please allow me to take your changes and have them in the modules on your behalf.

**Comment by moonrail** [comment]
Our fork is now too far off from upstream. Needs reevaluation on our side, therefore close for now.

**Pull request closed without merging**
